version: "3"
services:
  doe22:
    build:
      context: ./versions/python
      dockerfile: ./dockerfile
      args:
        DOE22PASSWORD: $DOE22PASSWORD
    container_name: dc-doe22
    image: grammyjiang/doe2:$DOE22VERSION
    networks:
      - doe22
    tty: true
    volumes:
      - /home/grammy-jiang/PycharmProjects/docker-doe22/sample:/root/.wine/drive_c/sample

networks:
  doe22:
    driver: bridge
